import { component$, useSignal, useStore, useTask$ } from '@builder.io/qwik';
import { DocumentHead, Link } from '@builder.io/qwik-city';
import { generateBlogIdFromTitle, generateBlogTitleFromId, getListOfBlogsFromFs } from '~/utils';



const BlogEntry = component$<{ blog: string, month: string }>(({ blog, month }) => {
  return (
    <div class="flex align-middle mt-3">
      <div class="w-24 text-lg text-slate-400 flex items-center">
        {month}
      </div>
      <a href={`/blogs/${generateBlogIdFromTitle(blog)}`}>
        <div class="highlight link">
          {blog}
        </div>
      </a>
    </div>
  )
})

// no question marks are allowed as blog titles
export default component$(() => {

  // as soon as the user comes to this page, I have to generate the list of blogs
  // this 'data' should be generated by looking at the filesystem at 'routes/blogs/*' 
  // all the directory names will be the id of the blogs
  const blogs = useStore<{ year: string, items: { month: string, blog: string }[] }[]>([])

  useTask$(() => {
    getListOfBlogsFromFs((res) => {
      if (res instanceof Error || !res || res.length == 0) {
        return
      }
      // res.date is 'Mon 12'
      // we can get Date from res.date by doing new Date(res.date+", 2012")
      let sortedRes = res.sort((a, b) => new Date(a?.date + ", " + a?.year) > new Date(b?.date + ", " + b?.year) ? -1 : 1)
      sortedRes.forEach(i => {
        if (i) {
          let idx = blogs.findIndex(b => b.year == i.year)
          if (idx > -1) {
            blogs[idx] = { ...blogs[idx], items: [...blogs[idx].items, { month: i.date, blog: i.blogId }], }
          } else {
            blogs.push({
              year: i.year,
              items: [{ month: i.date, blog: i.blogId }]
            })
          }
        }
      })
    })
  })

  return (
    <>
      <h1>
        Blogs
      </h1>
      {blogs.map(item => <>
        <h2> {item.year} </h2>
        {item.items.map(i => <BlogEntry blog={generateBlogTitleFromId(i.blog)} month={i.month} />)}
      </>)}
    </>
  );
});

export const head: DocumentHead = {
  title: "Archives - Nithish Karthik",
  meta: [
    {
      name: 'description',
      content: "Nithish Karthik's archive blogs",
    },
  ],
}
